Resources:

  DemoListoProEdSantosHnPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DemoListoProEdSantosHnPolicy
      Description: Permiso para permitir que nuestra lambda acceda a objetos en un bucket S3.
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource:
          - arn:aws:s3:::nombre-de-nuestro-bucket/*
          - arn:aws:s3:::nombre-de-nuestro-bucket

  DemoListoProEdSantosHnDynamoPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: DemoListoProEdSantosHnDynamoPolicy
      Description: Permiso para permitir que nuestra lambda Inserte y obtenga registros de Dynamo.
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:BatchGetItem
          - dynamodb:GetItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:BatchWriteItem
          - dynamodb:PutItem
          Resource: "arn:aws:dynamodb:{region}:{account_id}:table/ListoProTable"