service: nombre-de-proyecto-infra

provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage, 'dev'}
  region: ${self:custom.config.${self:custom.stage}.my-region}

custom:
  stage: ${opt:stage, 'dev'}
  
  config:
    dev:
      account_id: ''
      my-region: ${opt:region, 'us-east-2'}
      my_first_bucket: my-first-dev-bucket
      my_second_bucket: my-second-dev-bucket
    prd:
      account_id: ''
      my-region: ${opt:region, 'us-east-1'}
      my_first_bucket: prod-bucket-name-1
      my_second_bucket: prod-bucket-name-2



resources:
- ${file(s3.yml)}
